version: "3"

networks:
  loki:

volumes:
  grafana:

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - loki

  loki:
    image: grafana/loki:2.8.0
    labels:
      - traefik.http.routers.loki.rule=Host(`loki.localhost`)
      - traefik.http.middlewares.loki-auth.basicauth.users=test:$$2y$$12$$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG #username="test";password="test"
      - traefik.http.routers.loki.middlewares=loki-auth
    volumes:
      - ./config:/etc/loki/
    command: -config.file=/etc/loki/loki.yaml
    networks:
      - loki
    restart: always
    deploy:
      mode: replicated
      replicas: 3

  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler &&
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    expose:
      - 9000
    volumes:
      - ./.data/minio:/data
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    expose:
      - 3000
    labels:
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana:/var/lib/grafana
    networks:
      - loki
